# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calib <- function(Y, C, Z, mu_input, mu_dim, mu0_input, mu0_dim, S) {
    .Call('cremid_calib', PACKAGE = 'cremid', Y, C, Z, mu_input, mu_dim, mu0_input, mu0_dim, S)
}

fit <- function(Y, C, prior, mcmc, state) {
    .Call('cremid_fit', PACKAGE = 'cremid', Y, C, prior, mcmc, state)
}

